### ISSUE TITLE
Menu in combat not translated

### ISSUE THREAD

**Issue by Dragoonglue** [nleseul/ds6_pc98_trans#7]
This untranslated menu pops up after making a character auto-battle and then holding down [ESC], [SHIFT] or [NFER] before his turn.
![Dragon Slayer - The Legend of Heroes-240805-133531](https://github.com/user-attachments/assets/3e478795-008a-469b-968e-a68ef9d55661)

**Comment by nleseul** [comment]
Good catch! I obviously don't use the auto-combat feature very much. Thanks for logging it.

For your reference, until I get an update out, the options in that menu are "Combat settings" and "Run".

**Comment by nleseul** [comment]
Addressed by 2d32f8f93afa50dbe8003521624194a91a6f86a9.

(I'll wait a bit before publishing a new version with this fix, just in case people report other issues that should be included in the next release in the next few days.)
